CREATE TABLE user(
  id_user LONG AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(48) NOT NULL,
  password VARCHAR(60) NOT NULL,
  name VARCHAR(48)
);

CREATE TABLE role(
  id_role LONG AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(48) NOT NULL,
  description VARCHAR(48)
)